# Generated by Django 5.1.4 on 2024-12-31 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_projects_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='user_id',
            new_name='user',
        ),
    ]
